
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String 
  myUsername:
    Description: Any username
    Type: String 
  myPassword:
    Description: A password with at least 8 characters
    Type: String  
Resources:
 
  myDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnets to use for the DB"
      DBSubnetGroupName: "Subnet Group"
    
      SubnetIds:
      - subnet-0450bf5757e469a4b
      - subnet-0cea285b6b1fbd273
    
  MyDatabase: 
    Type: "AWS::RDS::DBInstance"
    Properties: 
      
      VPCSecurityGroups: [sg-0c27e067059ed389c]
      PubliclyAccessible: false
      MultiAZ: false
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: "mysql"
      MasterUsername: !Sub "${myUsername}"
      MasterUserPassword: !Sub "${myPassword}"
      DBSubnetGroupName: !Ref myDBSubnetGroup11
      Tags: 
        - 
          Key: "Name"
          Value: !Sub "${EnvironmentName} MS SQL RDS"
    DeletionPolicy: "Retain"